import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Categories from '@/ui/categories';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          maxWidth: '480px',
          margin: '0 auto',
          minHeight: '100vh',
        }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <div className="text-xl font-semibold">브랜드콘</div>
          <Categories />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
